import { Router } from "express";
import { getAllUsers, logOutUser, userSignin, userSignup, verifyUser } from "../controllers/userController.js";
import { authMiddleware } from "../middlewares/authMiddleware.js";
const userRouter=Router();
userRouter.post("/signup",userSignup);
userRouter.post("/signin",userSignin);
userRouter.get("/",getAllUsers);
userRouter.get("/auth-status",authMiddleware,verifyUser);
userRouter.get("/logout",authMiddleware,logOutUser);
export default userRouter;